import Head from 'next/head';
import Router from 'next/router';
import { useLayoutEffect, useState } from 'react';
import API from '../api/api';
import { init } from '../state/appState';

export default function Home() {
  const [list, setList] = useState([]);
  useLayoutEffect(() => {
    setList(API.Invoices.get());
  }, []);
  return (
    <div className="index_page">
      <Head>
        <title>On Developement!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Your Invoices</h1>
      <div className="list_cont">
        {list.map((item, index) => (
          <div>
            <div className="list" onClick={() => Router.push(`/app/${item.id._id}`)}>
              <p>
                {' '}
                <span>{index + 1}</span>
                {'   '}
                {item.id._id}
              </p>
            </div>
            <button
              onClick={() => {
                API.Invoices.del(index);
                setList(API.Invoices.get());
              }}
              style={{ padding: '0.5rem', aspectRatio: '1/1', width: '50px' }}
              type="button"
            >
              {' '}
              <i className="fas fa-trash    " />
            </button>
          </div>
        ))}
        {list.length <= 0 && <div>No Invoices</div>}
      </div>
      <br />
      <br />
      <br />
      <button
        onClick={async () => {
          const dt = await API.createInvoice(init);
          Router.push(`/app/${dt._id}`);
        }}
        style={{ padding: '0.5rem 1rem' }}
        type="button"
      >
        {' '}
        <i className="fas fa-plus" /> Add Invoice
      </button>
    </div>
  );
}
