import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>On Developement!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>On Developement!!</p>
      <button type="button">
        <Link href="/app">Click here to see the app</Link>
      </button>
      <img src="/inv.jpg" alt="dssdd" />
    </div>
  );
}
